on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry-pick-0-3:
    runs-on: ubuntu-latest
    name: Cherry pick into 0.3
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release-0.3') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v1.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: 0.3
          labels: |
            cherry-pick
